version: '3.5'
services:
  database:
    image: postgres:14.3-alpine
    env_file: 
      - .database.env
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
  test_database:
    image: postgres:14.3-alpine
    env_file: 
      - .test_database.env
    ports:
      - "6000:5432"
  