"""delete item

Revision ID: b92c9493ac0b
Revises: 78f8d703eb72
Create Date: 2023-07-27 09:24:43.774631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92c9493ac0b'
down_revision = '78f8d703eb72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_id', table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ingridients', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='item_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey'),
    sa.UniqueConstraint('name', name='item_name_key')
    )
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    # ### end Alembic commands ###
