"""cart_item del

Revision ID: 331515dd881d
Revises: bcf632492ce2
Create Date: 2023-07-27 15:06:10.085504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331515dd881d'
down_revision = 'bcf632492ce2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_item_id', table_name='cart_item')
    op.drop_table('cart_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='cart_item_cart_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='cart_item_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cart_item_pkey')
    )
    op.create_index('ix_cart_item_id', 'cart_item', ['id'], unique=False)
    # ### end Alembic commands ###
