"""metadata test

Revision ID: caad9ab048ae
Revises: 8605776fd9b1
Create Date: 2023-08-10 17:29:22.552276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caad9ab048ae'
down_revision = '8605776fd9b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
